#!/bin/bash

IFS='.' read -r -a PKG_VER_ARRAY <<< "${PKG_VERSION}"

sed -i.bak "s/libLTO.dylib/libLTO.${PKG_VER_ARRAY[0]}.dylib/g" lib/Driver/ToolChains/Darwin.cpp

mkdir build
cd build

cmake \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_PREFIX_PATH=$PREFIX \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_RTTI=ON \
  -DCLANG_INCLUDE_TESTS=OFF \
  -DCLANG_INCLUDE_DOCS=OFF \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_DOCS=OFF \
  -DLLVM_ENABLE_LIBXML2=OFF \
  -DCMAKE_AR:FILEPATH=${AR} \
  -DCMAKE_CXX:FILEPATH=${CXX} \
  -DCMAKE_LINKER:FILEPATH=${LD} \
  -DCMAKE_AR:FILEPATH=${AR} \
  -DCMAKE_AS:FILEPATH=${AS} \
  -DCMAKE_RANLIB:FILEPATH=${RANLIB} \
  -DCMAKE_ASM_COMPILER_AR:FILEPATH=${AR} \
  -DCMAKE_ASM_COMPILER_RANLIB:FILEPATH=${RANLIB} \
  -DCMAKE_INSTALL_NAME_TOOL:FILEPATH=${INSTALL_NAME_TOOL} \
  -DCMAKE_NM:FILEPATH=${NM} \
  -DCMAKE_OBJCOPY:FILEPATH=${OBJCOPY} \
  -DCMAKE_OBJDUMP:FILEPATH=${OBJDUMP} \
  -DCMAKE_STRIP:FILEPATH=${STRIP} \
  ..

make -j${CPU_COUNT}
