{% set version = "8.0.0" %}
{% set major_version = version.split(".")[0] %}
{% set sha256 = "084c115aab0084e63b23eee8c233abb6739c399e29966eaeccfc6e088e0b736b" %}
{% set build_number = 2 %}

package:
  name: clang_packages
  version: {{ version }}

source:
  url: http://llvm.org/releases/{{ version }}/cfe-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-Find-conda-gcc-installation.patch
    - patches/0002-Fix-sysroot-detection-for-linux.patch

build:
  number: {{ build_number }}
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}    # [not osx]
    - cmake >=3.4.3
    # Needed to unpack the source tarball
    - m2w64-xz  # [win]
    # "compiling .pyc files" fails without this
    - python >3
    # Building with ninja on windows for parallel builds
    - ninja  # [win]
    - make   # [unix]
  host:
    - libcxx {{c_compiler_version}}.*  # [osx]
    - llvmdev =={{ version }}

test:
  requires:
    - {{ compiler('cxx') }}   # [not osx]
    - cmake >=3.4.3
  files:
    - mytest.c
  commands:
    - $PREFIX/bin/clang --version  # [unix]
    - $PREFIX/bin/clang++ --version  # [unix]
    - $PREFIX/bin/clang-check --version  # [unix]

    - $PREFIX/bin/clang -v -c mytest.c      # [unix]
    - "%LIBRARY_BIN%/clang -v -c mytest.c"  # [win]

    - if not exist %LIBRARY_INC%\\clang\\Lex\\Lexer.h exit 1  # [win]
    - test -f $PREFIX/include/clang/Lex/Lexer.h      # [unix]
    - test -f $PREFIX/lib/libclangBasic.a            # [unix]


outputs:
  - name: clangdev
    script: install_clangdev.sh
    requirements:
      build:
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clang-tools", exact=True) }}
        - {{ pin_subpackage("libclang", exact=True) }}
      run:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clang-tools", exact=True) }}
        - {{ pin_subpackage("libclang", exact=True) }}
        - libcxx >={{c_compiler_version}}  # [osx]
      run_constrained:
        - llvm-meta =={{ version }}
        - llvmdev =={{ version }}

  - name: libclang
    script: install_libclang.sh
    requirements:
      build:
        - {{ compiler('cxx') }}    # [not osx]
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      run:
        - libcxx >={{c_compiler_version}}  # [osx]

  - name: clang
    script: install_clang.sh
    requirements:
      build:
        - {{ compiler('cxx') }}    # [not osx]
        - libcxx                   # [osx]
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      run:
        - libcxx >={{c_compiler_version}}  # [osx]

  - name: clang-tools
    script: install_clang_tools.sh
    requirements:
      build:
        # "compiling .pyc files" fails without this
        - python >3
        - {{ compiler('cxx') }}    # [not osx]
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - {{ pin_subpackage("clang", exact=True) }}
      run:
        - {{ pin_subpackage("clang", exact=True) }}
        - libcxx >={{c_compiler_version}}  # [osx]

  - name: python-clang
    build:
      noarch: python
      # Building this output using this recipe is only supported on unix
      # It can still be installed on Windows as it is marked as `noarch: python`
      skip: true  # [win]

    script: build_python_bindings.sh

    requirements:
      host:
        - python
      run:
        - python
        - clangdev =={{ version }}

    test:
      requires:
        - nose
      source_files:
        - bindings/python/tests
        - bindings/python/examples/cindex
      imports:
        - clang
        - clang.cindex
      commands:
        - cd bindings/python
        - cp tests/cindex/util.py tests
        - nosetests -v

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for Clang

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - jakirkham
    - mattwala
    - SylvainCorlay
